export { default as Footer } from './lib/footer/footer';
export { default as Header } from './lib/header/header';
export { default as Meta } from './lib/meta/meta';
export { default as EditorPlaceholder } from './lib/placeholders/editor/editor';
export { default as UploaderPlaceholder } from './lib/placeholders/uploader/uploader';
export { default as MainPanelPlaceholder } from './lib/placeholders/header/components/dropdowns/panels/main';
export { default as AssetItemPlaceholder } from './lib/placeholders/asset/item';
export { default as BundleItemPlaceholder } from './lib/placeholders/bundle/item';
export { default as CollectionItemPlaceholder } from './lib/placeholders/collection/item';
