name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch --no-tags --prune --depth=1 origin master

      - name: Install dependencies 📦
        run: yarn install --frozen-lockfile
      - name: NX lint workspace
        run: yarn nx workspace-lint
      - name: NX check format
        run: yarn nx format:check
      - name: NX lint affected code
        run: yarn nx affected --target=lint --parallel=3
      - name: NX test affected code and generate code coverage by Instanbul
        run: yarn nx affected --target=test --parallel=3 --ci --code-coverage
      - name: NX build app with using precached builds
        run: yarn nx affected --target=build --prod --parallel=3